### ISSUE TITLE
Unable to install from source

### ISSUE THREAD

**Issue by Slawcioo** [JarryShaw/PyPCAPKit#140] opened 2023-06-03 11:27 UTC
**Describe the bug**
When I tried to install current version with `pip install -e .` command. I got the error message:
  
  ` TypeError: expected str, bytes or os.PathLike object, not NoneType
      [end of output]`

**System information**
 - OS Version: Ubuntu 22.04.2 LTS
 - Python Version: Python 3.10.6
 - Python Implementation:  CPython

```
**Traceback stack**
   Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/user/workspace/PyPCAPKit/setup.py", line 105, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/user/workspace/PyPCAPKit/setup.py", line 92, in run
          refactor(os.path.join(self.install_lib, 'pcapkit'))
        File "/usr/lib/python3.10/posixpath.py", line 76, in join
          a = os.fspath(a)

```

**Expected behavior**
I expected the library to be installed.

**Additional context**

**Comment by JarryShaw** [comment] 2023-06-05 10:50
Cannot reproduce the error. Potentially resolved in version **1.0.2"".

**Closed by JarryShaw** 2023-06-05 10:50 UTC
Labels: bug
